### ISSUE TITLE
How to build on NixOS?

### ISSUE THREAD

**Issue by fionera** [NixOS/nix-idea#30]
Because the Build runs with the JetBrains JDK it throws a not found error because of linking issues. How to build it on NixOS?

**Comment by JojOatXGME** [comment]
Honestly, I'm currently not using NixOS while working on the project. I have not noticed the issue yet. I guess it might somehow be caused by one of the Gradle projects? Can you provide the full exception. You might need to add the `--stacktrace` option to your Gradle command.

**Comment by fionera** [comment]
The Stacktrace wont help much since its the typical binary issue:
```
Execution failed for task ':buildSearchableOptions'.
> A problem occurred starting process 'command '/home/fionera/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_9-linux-x64-b944.49/jbr/bin/java''
```

When I try to run it manually you see it more clearly:
```
[fionera@fionera-t580:~/src/Java/nix-idea]$ ls /home/fionera/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_9-linux-x64-b944.49/jbr/bin/java
/home/fionera/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_9-linux-x64-b944.49/jbr/bin/java

[fionera@fionera-t580:~/src/Java/nix-idea]$ /home/fionera/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_9-linux-x64-b944.49/jbr/bin/java
bash: /home/fionera/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbr-11_0_9-linux-x64-b944.49/jbr/bin/java: No such file or directory
```

**Comment by Mic92** [comment]
Maybe fhsUservenv or nix-ld help here.

**Comment by JojOatXGME** [comment]
I have reproduced the issue in a VM. It looks like you can use the `jetbrains.idea-community` derivation as a workaround. I may take a closer look on the weekend. I have pinned the issue for the time being since it might also help other persons who take a look at this repository.

```nix
# shell.nix
{ pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
  buildInputs = with pkgs; [
    jdk11
  ];
  IDEA_PATH = pkgs.jetbrains.idea-community + "/idea-community-2021.1.2";
}
```
```diff
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -44,8 +44,9 @@ dependencies {
 // Read more: https://github.com/JetBrains/gradle-intellij-plugin
 intellij {
     pluginName = pluginName
-    version = platformVersion
-    type = platformType
+    localPath = System.getenv("IDEA_PATH")
     downloadSources = platformDownloadSources.toBoolean()
     updateSinceUntilBuild = true
 }
```

**Comment by JojOatXGME** [comment]
I have made some research for potential solutions. The first one looks the most promising to me. I think I will prepare a pull request for that in a few days.

**Use IntelliJ from nixpkgs for build**

As shown in my last comment, it is possible to use the local installation of IntelliJ. The approach from my last comment might further be improved by two steps:

1. Set [`JavaExec.executable`] for the affected tasks to `pkgs.jetbrains.jdk + "/bin/java"` instead of changing `intellij.localPath`. This way, we use the IDE as declared in Gradle, but only replace the Java runtime under the hood. This makes the build more independent of the system configuration.

    ```kts
    withType<org.jetbrains.intellij.tasks.RunIdeBase> {
        executable = jetbrainsJdk.resolve("bin/java").toString()
    }
    ```

2. We might use a symlink to `pkgs.jetbrains.jdk` at a specific location in the worktree, so the user does not have to use a separate environment. This might avoid complications with IDEs if the developer wants to have multiple projects open at the same time.

**Using shell with buildFHSUserEnv**

I created a minimal configuration for [buildFHSUserEnv]. It did work initially, but for some reason it does not work anymore. While it still works if I run the executable manually, it does no-longer work if I run the executable through Gradle. I also noticed that disabling *nix-ld+ does not delete `/lib64/ld-linux-x86-64.so.2`, since I got "LD" not defined instead of "file not found".

Anyway, since you are basically loosing all your configuration in FHSUserEnv environments, I think it would not be a pleasant experience for development.

<details><summary><i>nix-shell configuration with buildFHSUserEnv</i></summary><p>

```nix
{ pkgs ? import <nixpkgs> {} }:
(pkgs.buildFHSUserEnv {
  name = "nix-idea-build-env";
  targetPkgs = pkgs: with pkgs; [
    jdk11
    # Required by the Gradle wrapper (gradlew)
    which
    # Required by JBR (JetBrains Runtime), which is downloaded and used by the
    # gradle-intellij-plugin.
    fontconfig
    freetype
    zlib
  ];
}).env
```
</p></details>

**Using nix-ld**

I have tested [nix-ld] and it seems to work fine. However, since it requires a package from outside `nixpkgs`, I would not use it as the first choice in our documentation. I also noticed that installing `nix-ld` causes `buildFHSUserEnv` to break. It looks like `buildFHSUserEnv` is not overriding 

<details><summary><i>nix-shell configuration for nix-ld</i></summary><p>

```nix
{ pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
  NIX_LD = builtins.readFile "${pkgs.stdenv.cc}/nix-support/dynamic-linker";
  NIX_LD_LIBRARY_PATH = with pkgs; lib.makeLibraryPath [
    # Required by the Gradle wrapper (gradlew)
    which
    # Required by JBR (JetBrains Runtime) and IDEA, which is downloaded and used
    # by the gradle-intellij-plugin.
    fontconfig
    freetype
    xorg.libX11
    xorg.libXext
    xorg.libXi
    xorg.libXrender
    xorg.libXtst
    zlib
  ];
  buildInputs = with pkgs; [
    jdk11
  ];
}
```
</p></details>

**Artifact transforms in Gradle**

It might also be possible to modify the binaries by using [artifact transforms] in Gradle. However, further examination would be necessary, and it is probably the most complicated solution.


[`JavaExec.executable`]:
<https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:executable>
"JavaExec - Gradle DSL Version 7.1.1"
[buildFHSUserEnv]:
<https://nixos.org/manual/nixpkgs/stable/#sec-fhs-environments>
"NixOS - Nixpkgs 21.05 manual"
[nix-ld]:
<https://github.com/Mic92/nix-ld>
"Mic92/nix-ld: Run unpatched dynamic binaries on NixOS"
[artifact transforms]:
<https://docs.gradle.org/current/userguide/artifact_transforms.html>
"Transforming dependency artifacts on resolution"

**Comment by JojOatXGME** [comment]
I created #31 to help users on NixOS to build the project. @fionera, if you are still interested, maybe you can try that out. You can find it on branch `build_on_nixos`.
